val = input('Digite algo\n >')
print('O tipo primitivo desse valor é', type(val))
print('Possui apenas espaços: ', val.isspace())
print('é numérico: ', val.isnumeric())
print('é alfabético: ', val.isalpha())
print('é alfanumérico: ', val.isalnum())
print('está em maiúsculas: ', val.isupper())
print('está em minúsculas: ', val.islower())
print('está capitalizado: ', val.istitle())
